# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: DineroAgentPooll

steps:
- script: sudo curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
  displayName: 'Install the Azure CLI'
  
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(Azure_Subscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az webapp up -n $(APP_NAME) --os-type Linux --resource-group $(Resource_Group_Name) --location $(Location) --sku B1 --runtime "python|3.6"'
    workingDirectory: 'src/'
  displayName: "Deploy application to Azure"